---
- name: Install nginx
  apt: name=nginx update_cache=yes state=present

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/sites-available/default
  notify: restart nginx
