---
- name: PHP | Add php-7.0 PPA
  apt_repository: repo='ppa:ondrej/php' update_cache=yes state=present

- name: Install php-fpm and deps
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - php7.0-fpm
    - php7.0-gd
    - php7.0-mysql

- name: Disable default pool
  command: mv /etc/php/7.0/fpm/pool.d/www.conf /etc/php/7.0/fpm/pool.d/www.disabled creates=/etc/php/7.0/fpm/pool.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php/7.0/fpm/pool.d/
  notify: restart php-fpm
