---
 - name: Backup MySQL with archive of main folder of mysql                                                            
   archive:                                                                                                           
     path: /var/WWW                                                                                             
     dest: /tmp/{{inventory_hostname}}_nginx-bkp_{{ '%Y-%m-%d' | strftime }}.tar.bz2                                            
   delegate_to: localhost  
